### ISSUE TITLE
failed to run makefile /could u please help me

### ISSUE THREAD

**Issue by DaicongChen** [pnggroup/libpng#502] opened 2023-11-28 10:35 UTC
ozone@DESKTOP-S0FVO33 /cygdrive/c/Users/ozone/Downloads/lens-undistortion-with-automatic-method-master (1)/lens-undistortion-with-automatic-method-master/libpng-libpng16
$ make check
rm -f scripts/symbols.out scripts/symbols.tf[12]
test -d scripts || mkdir scripts || test -d scripts
gcc -E -DHAVE_CONFIG_H -I. \
     -DPNGLIB_LIBNAME='PNG16_0' -DPNGLIB_VERSION='1.6.41.git' -DSYMBOL_PREFIX='' -DPNG_NO_USE_READ_MACROS -DPNG_BUILDING_SYMBOL_TABLE  scripts/symbols.c > scripts/symbols.tf1
gawk -f "./scripts/dfn.awk" out="scripts/symbols.tf2" scripts/symbols.tf1 1>&2
rm -f scripts/symbols.tf1
mv scripts/symbols.tf2 scripts/symbols.out
rm -f scripts/symbols.chk scripts/symbols.new
gawk -f ./scripts/checksym.awk ./scripts/symbols.def\
    of="scripts/symbols.new" scripts/symbols.out >&2
mv scripts/symbols.new scripts/symbols.chk
make  check-am
make[1]: Entering directory '/cygdrive/c/Users/ozone/Downloads/lens-undistortion-with-automatic-method-master (1)/lens-undistortion-with-automatic-method-master/libpng-libpng16'
depbase=`echo contrib/tools/pngfix.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
gcc -DHAVE_CONFIG_H -I.     -g -O2 -MT contrib/tools/pngfix.o -MD -MP -MF $depbase.Tpo -c -o contrib/tools/pngfix.o contrib/tools/pngfix.c &&\
mv -f $depbase.Tpo $depbase.Po
In file included from contrib/tools/../../png.h:330:0,
                 from contrib/tools/pngfix.c:44:
contrib/tools/../../pnglibconf.h:206:54: error: expected identifier or '(' befor
e '-' token
                                                 0
                                                      ^
make[1]: *** [Makefile:1227: contrib/tools/pngfix.o] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/ozone/Downloads/lens-undistortion-with-automatic-method-master (1)/lens-undistortion-with-automatic-method-master/libpng-libpng16'
make: *** [Makefile:2028: check] Error 2

**Comment by ctruta** [comment] 2023-12-07 13:31
Hello, I would like to help you but I cannot reproduce the error that you are seeing. Is your Cygwin installation 32-bit or 64-bit?

For example, the error line
```
contrib/tools/../../pnglibconf.h:206:54: error: expected identifier or '(' before '-' token
```
should not occur, because line 205 should end at column 44, and line 206 should end at column 38, as follows:
```
#define PNG_TEXT_Z_DEFAULT_COMPRESSION (-1)
#define PNG_TEXT_Z_DEFAULT_STRATEGY 0
```

Perhaps if you could please attach the content of `pnglibconf.h` to this bug report, I might be able to tell you more about what's going on.

Meanwhile, an alternative idea for you to try would be a clean and isolated libpng build, cloned directly from upstream, and without any interference from external projects such as `lens-undistortion-with-automatic-method`. I cannot say for sure whether the downstream project had anything to do with your error, so it would be a good idea to rule that out.

**Comment by jbowler** [comment] 2023-12-09 00:57
FWIW it's probably this github project:

https://github.com/tuuzhang/lens-undistortion-with-automatic-method

The project has local copies of libpng and zlib.  I only looked at it briefly but it would seem the libpng tree has been modified to implement the authors code.  The bug (if it is a bug) should be reported to the downstream code, i.e. https://github.com/tuuzhang

**Comment by rossburton** [comment] 2023-12-13 13:11
I see your build directory has `(1)` in:

```
ozone@DESKTOP-S0FVO33 /cygdrive/c/Users/ozone/Downloads/lens-undistortion-with-automatic-method-master (1)/lens-undistortion-with-automatic-method-master/libpng-libpng16
```

Try renaming that folder to remove the space and (1).

**Comment by jbowler** [comment] 2023-12-13 23:14
Off topic: spaces should be fine in the source directory so long as the build is done in the source directory or a sub-directory.  In fact the libpng build itself works just fine in a sibling directory however 'configure' will disallow this:

```
$ git clone libpng.git 'a b'
$ mkdir 'build'
$ cd 'build' && ../'a b'/configure # configure won't allow this
```

This is fine:
`$ cd 'build' && cmake '../a b' && make`

However (cmake) **make test** fails; the generated tests/*.cmake files can't handle those tests which use lists of files, the script tests/pngtest does not quote its arguments (this is actually dangerous; an overwrite outside the build directory could happen) and the pngstest tests say (last but one line of tests/pngstest) that the last line won't work if ${srcdir} has spaces.

The rule to follow is not to use a space in a path supplied directly to **cmake** or indirectly as a path to **configure**.  I think the other cases work.

On topic: this issue is because the ./pnglibconf.h file has been misgenerated.  One likely explanation is that the input data files used to generate it contain spurious <CR> characters and the 'gawk'  is expecting UNIX line endings in data files.

**Comment by ctruta** [comment] 2024-02-24 17:03
Thank you @jbowler and @rossburton for your responses.
Closing ticket.

**Closed by ctruta** 2024-02-24 17:03 UTC
